/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/api/v1/organizations": {
    /** Available Organizations */
    get: operations["available_organizations_api_v1_organizations_get"];
  };
  "/api/v1/organizations/{destination_organization_id}/ingredient-copy": {
    /** Copy */
    post: operations["copy_api_v1_organizations__destination_organization_id__ingredient_copy_post"];
  };
  "/api/v1/organizations/{destination_organization_id}/ingredient-copy-preview/{source_organization_id}/{ingredient_id}": {
    /** Preview */
    get: operations["preview_api_v1_organizations__destination_organization_id__ingredient_copy_preview__source_organization_id___ingredient_id__get"];
  };
  "/api/v1/organizations/{destination_organization_id}/recipe-copy": {
    /** Copy */
    post: operations["copy_api_v1_organizations__destination_organization_id__recipe_copy_post"];
  };
  "/api/v1/organizations/{organization_id}/events": {
    /** List Events */
    get: operations["list_events_api_v1_organizations__organization_id__events_get"];
  };
  "/api/v1/organizations/{organization_id}/events/{event_id}/archive/{snapshot_id}": {
    /** Get Archived Event */
    get: operations["get_archived_event_api_v1_organizations__organization_id__events__event_id__archive__snapshot_id__get"];
  };
  "/api/v1/organizations/{organization_id}/events/{event_id}/shopping-lists": {
    /** List Shopping Lists */
    get: operations["list_shopping_lists_api_v1_organizations__organization_id__events__event_id__shopping_lists_get"];
  };
  "/api/v1/organizations/{organization_id}/events/{event_id}/shopping-lists/{shopping_list_id}": {
    /** Get Shopping List */
    get: operations["get_shopping_list_api_v1_organizations__organization_id__events__event_id__shopping_lists__shopping_list_id__get"];
  };
  "/api/v1/organizations/{organization_id}/members": {
    /** Members */
    get: operations["members_api_v1_organizations__organization_id__members_get"];
  };
  "/api/v1/organizations/{organization_id}/members/{membership_id}/assign-organization-admin": {
    /** Assign Role */
    post: operations["assign_role_api_v1_organizations__organization_id__members__membership_id__assign_organization_admin_post"];
  };
  "/api/v1/organizations/{organization_id}/members/{membership_id}/remove": {
    /** Remove */
    post: operations["remove_api_v1_organizations__organization_id__members__membership_id__remove_post"];
  };
  "/api/v1/organizations/{organization_id}/members/{membership_id}/revoke-organization-admin": {
    /** Revoke Role */
    post: operations["revoke_role_api_v1_organizations__organization_id__members__membership_id__revoke_organization_admin_post"];
  };
  "/api/v1/organizations/{organization_id}/members/invitations": {
    /** Invite */
    post: operations["invite_api_v1_organizations__organization_id__members_invitations_post"];
  };
  "/api/v1/sync/bootstrap": {
    /** Bootstrap */
    post: operations["bootstrap_api_v1_sync_bootstrap_post"];
  };
  "/api/v1/sync/pull": {
    /** Pull Changes */
    post: operations["pull_changes_api_v1_sync_pull_post"];
  };
  "/api/v1/sync/push": {
    /** Push Changes */
    post: operations["push_changes_api_v1_sync_push_post"];
  };
  "/api/v1/system/organizations": {
    /** List All */
    get: operations["list_all_api_v1_system_organizations_get"];
    /** Create */
    post: operations["create_api_v1_system_organizations_post"];
  };
  "/api/v1/system/organizations/{organization_id}": {
    /** Edit */
    patch: operations["edit_api_v1_system_organizations__organization_id__patch"];
  };
  "/api/v1/system/organizations/{organization_id}/lifecycle": {
    /** Lifecycle */
    post: operations["lifecycle_api_v1_system_organizations__organization_id__lifecycle_post"];
  };
  "/api/v1/system/organizations/access": {
    /** Access */
    get: operations["access_api_v1_system_organizations_access_get"];
  };
  "/auth/dummy/identities": {
    /** List Dummy Identities */
    get: operations["list_dummy_identities_auth_dummy_identities_get"];
  };
  "/auth/dummy/session": {
    /** Create Dummy Session */
    post: operations["create_dummy_session_auth_dummy_session_post"];
  };
  "/auth/session": {
    /** Current Identity */
    get: operations["current_identity_auth_session_get"];
  };
  "/auth/session/locale": {
    /** Set Locale */
    patch: operations["set_locale_auth_session_locale_patch"];
  };
  "/auth/session/logout": {
    /** Logout */
    post: operations["logout_auth_session_logout_post"];
  };
  "/health/live": {
    /** Live */
    get: operations["live_health_live_get"];
  };
  "/health/ready": {
    /** Ready */
    get: operations["ready_health_ready_get"];
  };
  "/media/receipt-attachments": {
    /** Create Attachment */
    post: operations["create_attachment_media_receipt_attachments_post"];
  };
  "/media/receipt-attachments/{attachment_id}": {
    /** Download Attachment */
    get: operations["download_attachment_media_receipt_attachments__attachment_id__get"];
    /** Upload Attachment */
    put: operations["upload_attachment_media_receipt_attachments__attachment_id__put"];
  };
  "/media/receipt-attachments/{attachment_id}/lifecycle": {
    /** Change Attachment Lifecycle */
    post: operations["change_attachment_lifecycle_media_receipt_attachments__attachment_id__lifecycle_post"];
  };
  "/media/receipt-attachments/{attachment_id}/status": {
    /** Attachment Status */
    get: operations["attachment_status_media_receipt_attachments__attachment_id__status_get"];
  };
  "/media/receipt-attachments/{attachment_id}/upload-ticket": {
    /** Issue Upload Ticket */
    post: operations["issue_upload_ticket_media_receipt_attachments__attachment_id__upload_ticket_post"];
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    /** AttachmentLifecycleRequest */
    AttachmentLifecycleRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /**
       * Operation
       * @enum {string}
       */
      operation: "retire" | "restore";
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /**
       * Receipt Id
       * Format: uuid
       */
      receipt_id: string;
    };
    /** AttachmentStatusResponse */
    AttachmentStatusResponse: {
      /**
       * Attachment Id
       * Format: uuid
       */
      attachment_id: string;
      /** Byte Size */
      byte_size: number | null;
      /** Content Hash */
      content_hash: string | null;
      /** Media Type */
      media_type: string | null;
      /** Pixel Height */
      pixel_height: number | null;
      /** Pixel Width */
      pixel_width: number | null;
      /** Retired */
      retired: boolean;
      /** Source Byte Size */
      source_byte_size: number | null;
      /** Source Content Hash */
      source_content_hash: string | null;
      /** Storage State */
      storage_state: string;
    };
    /** AvailableOrganizationListResponse */
    AvailableOrganizationListResponse: {
      /** Organizations */
      organizations: components["schemas"]["AvailableOrganizationResponse"][];
    };
    /** AvailableOrganizationResponse */
    AvailableOrganizationResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** BootstrapRecordResponse */
    BootstrapRecordResponse: {
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /** Entity Kind */
      entity_kind: string;
      /**
       * Operation
       * @constant
       */
      operation: "upsert";
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
    };
    /** BootstrapRequest */
    BootstrapRequest: {
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
    };
    /** BootstrapResponse */
    BootstrapResponse: {
      /** Cursor */
      cursor: string;
      /** Records */
      records: components["schemas"]["BootstrapRecordResponse"][];
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string;
      /**
       * Sync Schema Version
       * @constant
       */
      sync_schema_version: 1;
    };
    /** ClockSkewWarningResponse */
    ClockSkewWarningResponse: {
      /** Difference Seconds */
      difference_seconds: number;
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string;
    };
    /** CreateAttachmentRequest */
    CreateAttachmentRequest: {
      /**
       * Attachment Id
       * Format: uuid
       */
      attachment_id: string;
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /** Media Type */
      media_type: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Position Key */
      position_key: string;
      /**
       * Receipt Id
       * Format: uuid
       */
      receipt_id: string;
    };
    /** CreateAttachmentResponse */
    CreateAttachmentResponse: {
      /**
       * Attachment Id
       * Format: uuid
       */
      attachment_id: string;
      /**
       * Ticket Expires At
       * Format: date-time
       */
      ticket_expires_at: string;
      /** Ticket Secret */
      ticket_secret: string;
    };
    /** CreatedOrganizationResponse */
    CreatedOrganizationResponse: {
      /** Default Currency */
      default_currency: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** CreateOrganizationRequest */
    CreateOrganizationRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Default Currency
       * @default CZK
       */
      default_currency?: string;
      /** Description */
      description?: string | null;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Name */
      name: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
    };
    /** CurrentIdentityResponse */
    CurrentIdentityResponse: {
      /** Display Name */
      display_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Preferred Locale
       * @enum {string}
       */
      preferred_locale: "cs" | "en";
      /** Verified Email */
      verified_email: string;
    };
    /** DummyIdentityListResponse */
    DummyIdentityListResponse: {
      /** Identities */
      identities: components["schemas"]["DummyIdentityResponse"][];
    };
    /** DummyIdentityResponse */
    DummyIdentityResponse: {
      /** Display Name */
      display_name: string;
      /** Subject */
      subject: string;
    };
    /** EventArchiveSnapshotResponse */
    EventArchiveSnapshotResponse: {
      /** Archive Schema Version */
      archive_schema_version: number;
      /** Content Hash */
      content_hash: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
    };
    /** EventListResponse */
    EventListResponse: {
      /** Events */
      events: components["schemas"]["EventSummaryResponse"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** EventSummaryResponse */
    EventSummaryResponse: {
      /** Archived At */
      archived_at: string | null;
      /** Base Expected Attendance */
      base_expected_attendance: number;
      /** Budget Amount */
      budget_amount: string;
      /** Currency */
      currency: string;
      /** Current Archive Snapshot Id */
      current_archive_snapshot_id: string | null;
      /** End Date */
      end_date: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Lifecycle */
      lifecycle: string;
      /** Name */
      name: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Start Date */
      start_date: string;
    };
    /** FinalizeAttachmentResponse */
    FinalizeAttachmentResponse: {
      /**
       * Attachment Id
       * Format: uuid
       */
      attachment_id: string;
      /** Byte Size */
      byte_size: number;
      /** Media Type */
      media_type: string;
      /** Pixel Height */
      pixel_height: number;
      /** Pixel Width */
      pixel_width: number;
      /** Storage State */
      storage_state: string;
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status?: "ok";
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IngredientCopyMappingRequest */
    IngredientCopyMappingRequest: {
      /** Destination Id */
      destination_id: string | null;
      /**
       * Kind
       * @enum {string}
       */
      kind: "canonical_unit" | "default_store_section" | "dietary_tag";
      /**
       * Source Id
       * Format: uuid
       */
      source_id: string;
    };
    /** IngredientCopyPreviewResponse */
    IngredientCopyPreviewResponse: {
      /**
       * Canonical Unit Id
       * Format: uuid
       */
      canonical_unit_id: string;
      /** Default Store Section Id */
      default_store_section_id: string | null;
      /**
       * Destination Organization Id
       * Format: uuid
       */
      destination_organization_id: string;
      /** Dietary Tag Ids */
      dietary_tag_ids: string[];
      /** Mapping Requirements */
      mapping_requirements: components["schemas"]["MappingRequirementResponse"][];
      /** Precondition Fingerprint */
      precondition_fingerprint: string;
      /**
       * Source Ingredient Id
       * Format: uuid
       */
      source_ingredient_id: string;
      /** Source Name */
      source_name: string;
      /**
       * Source Organization Id
       * Format: uuid
       */
      source_organization_id: string;
      /**
       * Source Version Id
       * Format: uuid
       */
      source_version_id: string;
    };
    /** IngredientCopyRequest */
    IngredientCopyRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Ingredient Id
       * Format: uuid
       */
      ingredient_id: string;
      /** Logical Operation Id */
      logical_operation_id?: string | null;
      /** Mappings */
      mappings: components["schemas"]["IngredientCopyMappingRequest"][];
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Precondition Fingerprint */
      precondition_fingerprint: string;
      /**
       * Source Organization Id
       * Format: uuid
       */
      source_organization_id: string;
    };
    /** IngredientCopyResultResponse */
    IngredientCopyResultResponse: {
      /**
       * Canonical Unit Id
       * Format: uuid
       */
      canonical_unit_id: string;
      /** Default Store Section Id */
      default_store_section_id: string | null;
      /**
       * Destination Ingredient Id
       * Format: uuid
       */
      destination_ingredient_id: string;
      /**
       * Destination Organization Id
       * Format: uuid
       */
      destination_organization_id: string;
      /**
       * Destination Version Id
       * Format: uuid
       */
      destination_version_id: string;
      /** Dietary Tag Ids */
      dietary_tag_ids: string[];
      /** First Change Sequence */
      first_change_sequence: number;
      /** Last Change Sequence */
      last_change_sequence: number;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Replayed */
      replayed: boolean;
      /**
       * Source Ingredient Id
       * Format: uuid
       */
      source_ingredient_id: string;
      /** Source Name */
      source_name: string;
      /**
       * Source Organization Id
       * Format: uuid
       */
      source_organization_id: string;
      /**
       * Source Version Id
       * Format: uuid
       */
      source_version_id: string;
    };
    /** InviteMemberRequest */
    InviteMemberRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /** Invited Email */
      invited_email: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
    };
    /** MappingRequirementResponse */
    MappingRequirementResponse: {
      /** Kind */
      kind: string;
      /** Seed Key */
      seed_key?: string | null;
      /**
       * Source Id
       * Format: uuid
       */
      source_id: string;
    };
    /** MembershipListResponse */
    MembershipListResponse: {
      /** Memberships */
      memberships: components["schemas"]["MembershipResponse"][];
    };
    /** MembershipMutationResponse */
    MembershipMutationResponse: {
      /**
       * Membership Id
       * Format: uuid
       */
      membership_id: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Replayed */
      replayed: boolean;
      /** Role */
      role?: string | null;
      /** State */
      state: string;
    };
    /** MembershipResponse */
    MembershipResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Invited Email */
      invited_email: string;
      /** Role */
      role: string;
      /** State */
      state: string;
    };
    /** OrganizationEditRequest */
    OrganizationEditRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Default Currency
       * @default CZK
       */
      default_currency?: string;
      /** Description */
      description?: string | null;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Name */
      name: string;
    };
    /** OrganizationLifecycleRequest */
    OrganizationLifecycleRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /**
       * Operation
       * @enum {string}
       */
      operation: "retire" | "restore";
    };
    /** PullChangesRequest */
    PullChangesRequest: {
      /** Cursor */
      cursor?: string | null;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /**
       * Transaction Group Limit
       * @default 100
       */
      transaction_group_limit?: number;
    };
    /** PullChangesResponse */
    PullChangesResponse: {
      /** Next Cursor */
      next_cursor: string | null;
      /** Oldest Available At */
      oldest_available_at: string | null;
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "bootstrap_required";
      /**
       * Sync Schema Version
       * @constant
       */
      sync_schema_version: 1;
      /** Transaction Groups */
      transaction_groups: components["schemas"]["SyncTransactionGroupResponse"][];
    };
    /** PushChangesResponse */
    PushChangesResponse: {
      /** Change Cursor */
      change_cursor: string;
      clock_skew_warning:
        | components["schemas"]["ClockSkewWarningResponse"]
        | null;
      /** Outcomes */
      outcomes: components["schemas"]["PushCommandOutcomeResponse"][];
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string;
      /**
       * Sync Schema Version
       * @constant
       */
      sync_schema_version: 1;
    };
    /** PushCommandErrorResponse */
    PushCommandErrorResponse: {
      /** Code */
      code: string;
      /** Field Violations */
      field_violations: {
        [key: string]: string;
      }[];
      /** Retry Same Identity */
      retry_same_identity: boolean;
    };
    /** PushCommandOutcomeResponse */
    PushCommandOutcomeResponse: {
      /** Command Kind */
      command_kind: string;
      error: components["schemas"]["PushCommandErrorResponse"] | null;
      /** First Change Sequence */
      first_change_sequence: number | null;
      /** Last Change Sequence */
      last_change_sequence: number | null;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Replayed */
      replayed: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "accepted" | "partially_superseded" | "rejected";
    };
    /** RecipeCopyRequest */
    RecipeCopyRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Destination Recipe Id
       * Format: uuid
       */
      destination_recipe_id: string;
      /**
       * Destination Recipe Version Id
       * Format: uuid
       */
      destination_recipe_version_id: string;
      /** Ingredient Version Mappings */
      ingredient_version_mappings: {
        [key: string]: string;
      };
      /** Logical Operation Id */
      logical_operation_id?: string | null;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Preferred Display Unit Mappings */
      preferred_display_unit_mappings: {
        [key: string]: string;
      };
      /** Recipe Tag Mappings */
      recipe_tag_mappings: {
        [key: string]: string;
      };
      /** Scaling Unit Mappings */
      scaling_unit_mappings: {
        [key: string]: string;
      };
      /**
       * Source Current Recipe Version Id
       * Format: uuid
       */
      source_current_recipe_version_id: string;
      /**
       * Source Organization Id
       * Format: uuid
       */
      source_organization_id: string;
      /**
       * Source Recipe Id
       * Format: uuid
       */
      source_recipe_id: string;
    };
    /** RecipeCopyResultResponse */
    RecipeCopyResultResponse: {
      /**
       * Destination Organization Id
       * Format: uuid
       */
      destination_organization_id: string;
      /**
       * Destination Recipe Id
       * Format: uuid
       */
      destination_recipe_id: string;
      /**
       * Destination Recipe Version Id
       * Format: uuid
       */
      destination_recipe_version_id: string;
      /** First Change Sequence */
      first_change_sequence: number;
      /** Last Change Sequence */
      last_change_sequence: number;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Replayed */
      replayed: boolean;
      /**
       * Source Organization Id
       * Format: uuid
       */
      source_organization_id: string;
      /**
       * Source Recipe Id
       * Format: uuid
       */
      source_recipe_id: string;
      /**
       * Source Recipe Version Id
       * Format: uuid
       */
      source_recipe_version_id: string;
    };
    /** RemoveMemberRequest */
    RemoveMemberRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
    };
    /** SelectDummyIdentityRequest */
    SelectDummyIdentityRequest: {
      /** Subject */
      subject: string;
    };
    /** SetLocaleRequest */
    SetLocaleRequest: {
      /**
       * Preferred Locale
       * @enum {string}
       */
      preferred_locale: "cs" | "en";
    };
    /** ShoppingListSummariesResponse */
    ShoppingListSummariesResponse: {
      /** Next Cursor */
      next_cursor: string | null;
      /** Shopping Lists */
      shopping_lists: components["schemas"]["ShoppingListSummaryResponse"][];
    };
    /** ShoppingListSummaryResponse */
    ShoppingListSummaryResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Current Generation Revision Id */
      current_generation_revision_id: string | null;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /** Generated At */
      generated_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ingredient Row Count */
      ingredient_row_count: number;
      /** Name */
      name: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Source Scheduled Recipe Count */
      source_scheduled_recipe_count: number;
    };
    /** SyncRecordResponse */
    SyncRecordResponse: {
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /** Entity Kind */
      entity_kind: string;
      /** Operation */
      operation: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Sequence */
      sequence: number;
    };
    /** SyncTransactionGroupResponse */
    SyncTransactionGroupResponse: {
      /** First Sequence */
      first_sequence: number;
      /** Last Sequence */
      last_sequence: number;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /** Records */
      records: components["schemas"]["SyncRecordResponse"][];
    };
    /** SystemOrganizationResponse */
    SystemOrganizationResponse: {
      /** Default Currency */
      default_currency: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Retired At */
      retired_at: string | null;
      /** Retired By User Id */
      retired_by_user_id: string | null;
    };
    /** TicketRequest */
    TicketRequest: {
      /**
       * Client Installation Id
       * Format: uuid
       */
      client_installation_id: string;
      /**
       * Client Wall Time
       * Format: date-time
       */
      client_wall_time: string;
      /**
       * Mutation Id
       * Format: uuid
       */
      mutation_id: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /**
       * Receipt Id
       * Format: uuid
       */
      receipt_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = {
  /** Available Organizations */
  available_organizations_api_v1_organizations_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AvailableOrganizationListResponse"];
        };
      };
    };
  };
  /** Copy */
  copy_api_v1_organizations__destination_organization_id__ingredient_copy_post: {
    parameters: {
      path: {
        destination_organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngredientCopyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IngredientCopyResultResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Preview */
  preview_api_v1_organizations__destination_organization_id__ingredient_copy_preview__source_organization_id___ingredient_id__get: {
    parameters: {
      path: {
        destination_organization_id: string;
        source_organization_id: string;
        ingredient_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IngredientCopyPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Copy */
  copy_api_v1_organizations__destination_organization_id__recipe_copy_post: {
    parameters: {
      path: {
        destination_organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeCopyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecipeCopyResultResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Events */
  list_events_api_v1_organizations__organization_id__events_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        page_size?: number;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EventListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Archived Event */
  get_archived_event_api_v1_organizations__organization_id__events__event_id__archive__snapshot_id__get: {
    parameters: {
      path: {
        organization_id: string;
        event_id: string;
        snapshot_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EventArchiveSnapshotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Shopping Lists */
  list_shopping_lists_api_v1_organizations__organization_id__events__event_id__shopping_lists_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        page_size?: number;
      };
      path: {
        organization_id: string;
        event_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ShoppingListSummariesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Shopping List */
  get_shopping_list_api_v1_organizations__organization_id__events__event_id__shopping_lists__shopping_list_id__get: {
    parameters: {
      path: {
        organization_id: string;
        event_id: string;
        shopping_list_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ShoppingListSummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Members */
  members_api_v1_organizations__organization_id__members_get: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Assign Role */
  assign_role_api_v1_organizations__organization_id__members__membership_id__assign_organization_admin_post: {
    parameters: {
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipMutationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove */
  remove_api_v1_organizations__organization_id__members__membership_id__remove_post: {
    parameters: {
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipMutationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revoke Role */
  revoke_role_api_v1_organizations__organization_id__members__membership_id__revoke_organization_admin_post: {
    parameters: {
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipMutationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Invite */
  invite_api_v1_organizations__organization_id__members_invitations_post: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipMutationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Bootstrap */
  bootstrap_api_v1_sync_bootstrap_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BootstrapRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BootstrapResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Pull Changes */
  pull_changes_api_v1_sync_pull_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PullChangesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PullChangesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Push Changes */
  push_changes_api_v1_sync_push_post: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * Client Installation Id
           * Format: uuid
           */
          client_installation_id: string;
          /** Commands */
          commands: $defs["PushCommandRequest"][];
          /**
           * Organization Id
           * Format: uuid
           */
          organization_id: string;
          /**
           * Request Sent At
           * Format: date-time
           */
          request_sent_at: string;
          /**
           * Sync Schema Version
           * @constant
           */
          sync_schema_version: 1;
          $defs: {
            /**
             * PushCommandRequest
             * @description Forward-compatible command envelope; each known payload is validated below.
             */
            PushCommandRequest: {
              /**
               * Client Wall Time
               * Format: date-time
               */
              client_wall_time: string;
              /** Command Kind */
              command_kind: string;
              /**
               * Command Schema Version
               * @constant
               */
              command_schema_version: 1;
              /**
               * Mutation Id
               * Format: uuid
               */
              mutation_id: string;
              /** Payload */
              payload: {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PushChangesResponse"];
        };
      };
    };
  };
  /** List All */
  list_all_api_v1_system_organizations_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SystemOrganizationResponse"][];
        };
      };
    };
  };
  /** Create */
  create_api_v1_system_organizations_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrganizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CreatedOrganizationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Edit */
  edit_api_v1_system_organizations__organization_id__patch: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationEditRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SystemOrganizationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Lifecycle */
  lifecycle_api_v1_system_organizations__organization_id__lifecycle_post: {
    parameters: {
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationLifecycleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SystemOrganizationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Access */
  access_api_v1_system_organizations_access_get: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /** List Dummy Identities */
  list_dummy_identities_auth_dummy_identities_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DummyIdentityListResponse"];
        };
      };
    };
  };
  /** Create Dummy Session */
  create_dummy_session_auth_dummy_session_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SelectDummyIdentityRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Current Identity */
  current_identity_auth_session_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CurrentIdentityResponse"];
        };
      };
    };
  };
  /** Set Locale */
  set_locale_auth_session_locale_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetLocaleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CurrentIdentityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_auth_session_logout_post: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /** Live */
  live_health_live_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Ready */
  ready_health_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Create Attachment */
  create_attachment_media_receipt_attachments_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAttachmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CreateAttachmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Download Attachment */
  download_attachment_media_receipt_attachments__attachment_id__get: {
    parameters: {
      query: {
        organization_id: string;
      };
      path: {
        attachment_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload Attachment */
  upload_attachment_media_receipt_attachments__attachment_id__put: {
    parameters: {
      path: {
        attachment_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FinalizeAttachmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Change Attachment Lifecycle */
  change_attachment_lifecycle_media_receipt_attachments__attachment_id__lifecycle_post: {
    parameters: {
      path: {
        attachment_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttachmentLifecycleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Attachment Status */
  attachment_status_media_receipt_attachments__attachment_id__status_get: {
    parameters: {
      query: {
        organization_id: string;
        receipt_id: string;
      };
      path: {
        attachment_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Issue Upload Ticket */
  issue_upload_ticket_media_receipt_attachments__attachment_id__upload_ticket_post: {
    parameters: {
      path: {
        attachment_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CreateAttachmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
};
